---
- name: FTP Installation on CentOS
  yum:
   name: vsftpd
   state: latest
   update_cache: yes

- name: FTP server startup
  service:
   name: vsftpd
   state: started
   enabled: yes

- name: FTP user
  user:
   name: '{{ user }}'
   password: '{{ ftp_pass }}'

- name: Denying access for user
  lineinfile:
   path: /etc/ssh/sshd_config
   line: "DenyUsers '{{ user }}'"
  register: successfully_denied

- name: SSHD service restart
  service:
   name: sshd
   state: restarted
  when: successfully_denied.changed

- name: Default configuration file
  copy:
   src: /etc/vsftpd/vsftpd.conf
   dest: /etc/vsftpd/vsftpd.conf.default
   remote_src: True
 
- name: Limiting FTP users 
  replace:
   path: /etc/vsftpd/vsftpd.conf
   regexp: '#chroot_local_user=YES'
   replace: 'chroot_local_user=YES'

- name: FTP configure file
  lineinfile:
   path: /etc/vsftpd/vsftpd.conf
   line: '{{ ftp_config }}'

- name: Restart Vsftpd
  service:
   name: vsftpd
   state: restarted
# tasks file for roles/centosftp